export const THEME = {
  colors: {
    primary: '#CDBE91',
    secondary: '#F0E6D2',
    goldOne: '#F0E6D2',
    goldTwo: '#C8AA6E',
    goldThree: '#C8AA6E',
    goldFour: '#C89B3C',
    goldFive: '#785A28',
    goldSix: '#463714',
    goldSeven: '#32281E',
    bgDark: 'rgba(25, 0, 0, 1.0)',
    rpColor: '#d8ad00',
    beColor: '#0ACBE6',
  },
  audioUrls: {
    menuClick: 'https://github.com/jonylazarte/resources/raw/refs/heads/main/general/menu-click.mp3',
    confirmButtonClick: '/general/confirm-button-click.mp3',
    confirmButtonHover: '/general/confirm-button-hover.mp3',
    confirmButtonCancel: '/general/confirm-button-cancel-click.mp3',
    findMatchButtonClick: '/general/find-match-button-click.mp3',
    findMatchButtonHover: '/general/find-match-button-hover.mp3',
    buttonPlayClick: '/general/button-play-click.mp3',
    buttonPlayHover: '/general/button-play-hover.mp3',
    wildMusicPvp: 'https://github.com/jonylazarte/resources/raw/refs/heads/main/wild_4.ogg',
    wildMusicIa: 'https://github.com/jonylazarte/resources/raw/refs/heads/main/wild_3.ogg',
  },
  socketEvents: {
    AUTHENTICATE: 'authenticate',
    USER_LIST: 'user-list',
    CHAT_MESSAGE: 'chat-message',
    START_MATCH: 'start-match',
    BATTLE_MAILBOX: 'battle-mailbox',
    BATTLE_REQUEST: 'battle-request',
    JOIN_ROOM: 'join-room',
    LEAVE_ROOM: 'leave-room',
    SELECT_POKEMON: 'selectpokemon',
    SET_POKEMON: 'setpokemon',
    PLAYER_READY: 'player-ready',
    ATTACK: 'attack',
    USER_JOINED: 'USER JOINED',
    USER_OUT: 'USER-OUT',
    FIND_OPPONENT: 'find-opponent',
  }
};
